name: Lint

on:
  push:

jobs:
  check-ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/lint-install
      - name: Run ruff
        run: |
          make check-ruff

  check-black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/lint-install
      - name: Run black
        run: |
          make check-black

  check-isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/lint-install
      - name: Run isort
        run: |
          make check-isort

  check-mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/lint-install
      - name: Run mypy
        run: |
          make check-mypy

  check-pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/lint-install
      - name: Install dependencies
        run: |
          make install-dev SYNC=""
      - name: Run pylint
        run: |
          make check-pylint
